# Generated by Django 5.2.7 on 2025-12-07 13:48

import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.manager
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        help_text='Аватарка пользователя.',
                        upload_to=users.models.Profile.image_path,
                        verbose_name='аватарка',
                    ),
                ),
                (
                    'birthday',
                    models.DateField(
                        blank=True, help_text='Дата рождения пользователя.', null=True, verbose_name='дата рождения'
                    ),
                ),
                ('location', models.CharField(blank=True, help_text='Город (или страна) проживания пользователя.')),
                (
                    'attempts_count',
                    models.PositiveBigIntegerField(
                        default=0, help_text='Количество попыток входа в систему', verbose_name='попытки'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(db_index=True, max_length=500, verbose_name='ID новости')),
                ('title', models.CharField(max_length=500, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на новость')),
                (
                    'image_url',
                    models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение'),
                ),
                ('source_name', models.CharField(max_length=200, verbose_name='Название источника')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID источника')),
                ('creator', models.CharField(blank=True, max_length=200, null=True, verbose_name='Автор')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('tags', models.JSONField(default=list, help_text='Теги для поиска и фильтрации', verbose_name='Теги')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorite_articles',
                        to='users.user',
                        verbose_name='пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Избранная новость',
                'verbose_name_plural': 'Избранные новости',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='users_favor_user_id_fdd181_idx'),
                    models.Index(fields=['user', 'category'], name='users_favor_user_id_30912a_idx'),
                ],
                'unique_together': {('user', 'article_id')},
            },
        ),
    ]
