# Generated by Django 5.2.7 on 2025-12-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteArticle',
        ),
    ]
