# Generated by Django 5.2.7 on 2025-12-18 17:05

import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_favoritearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(
                blank=True,
                help_text='Дата рождения пользователя.',
                null=True,
                validators=[users.validators.ValidateBirthdayDate()],
                verbose_name='дата рождения',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Аватарка пользователя.',
                null=True,
                upload_to=users.models.Profile.image_path,
                verbose_name='аватарка',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(
                blank=True, help_text='Город (или страна) проживания пользователя.', null=True
            ),
        ),
    ]
