# Generated by Django 5.2.7 on 2025-12-19 09:49

import django.db.models.deletion
import users.models
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_birthday_alter_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_categories',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Favorite categories',
                verbose_name='favorite categories',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='attempts_count',
            field=models.PositiveBigIntegerField(
                default=0, help_text='Number of login attempts', verbose_name='attempts'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(
                blank=True,
                help_text='User date of birth.',
                null=True,
                validators=[users.validators.ValidateBirthdayDate()],
                verbose_name='date of birth',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='User avatar.',
                null=True,
                upload_to=users.models.Profile.image_path,
                verbose_name='avatar',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(
                blank=True, help_text='The user city (or country) of residence.', null=True
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
