# Generated by Django 5.2.7 on 2025-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_profile_favorite_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_at',
            field=models.DateTimeField(
                editable=False,
                help_text='account was deactivated',
                null=True,
                verbose_name='deactivate in',
            ),
        ),
    ]
