# Generated by Django 5.2.7 on 2025-12-24 17:56

import django.db.models.deletion
import users.models
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_blocked_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attempts_count',
            field=models.PositiveBigIntegerField(
                default=0, help_text='Number_of_login_attempts', verbose_name='Attempts'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(
                blank=True,
                help_text='User_date_of_birth',
                null=True,
                validators=[users.validators.ValidateBirthdayDate()],
                verbose_name='Date_of_birth',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_categories',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Favorite_categories',
                verbose_name='Favorite_categories',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='User_avatar',
                null=True,
                upload_to=users.models.Profile.image_path,
                validators=[users.validators.ValidateMaxFileSize()],
                verbose_name='Avatar',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='location_help_text', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
