# Generated by Django 5.2.7 on 2025-12-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_favoritearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(verbose_name='заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержание')),
                ('url', models.URLField(verbose_name='ссылка на новость')),
                (
                    'urlToImage',
                    models.URLField(blank=True, null=True, verbose_name='ссылка на изображение'),
                ),
                ('source', models.CharField(verbose_name='название источника')),
                ('author', models.CharField(blank=True, null=True, verbose_name='автор')),
                ('publishedAt', models.DateTimeField(verbose_name='дата публикации')),
                ('category', models.CharField(blank=True, null=True, verbose_name='категория')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorite_articles',
                        to='users.user',
                        verbose_name='пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'избранная новость',
                'verbose_name_plural': 'избранные новости',
                'ordering': ['-publishedAt'],
                'indexes': [
                    models.Index(
                        fields=['user', 'publishedAt'], name='news_favori_user_id_4bbfec_idx'
                    ),
                    models.Index(
                        fields=['user', 'category'], name='news_favori_user_id_eef30d_idx'
                    ),
                ],
                'unique_together': {('user', 'url')},
            },
        ),
    ]
