# Generated by Django 5.2.7 on 2025-12-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('users', '0002_delete_favoritearticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritearticle',
            options={
                'ordering': ['-published_at'],
                'verbose_name': 'избранная новость',
                'verbose_name_plural': 'избранные новости',
            },
        ),
        migrations.RemoveIndex(
            model_name='favoritearticle',
            name='news_favori_user_id_4bbfec_idx',
        ),
        migrations.RenameField(
            model_name='favoritearticle',
            old_name='publishedAt',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='favoritearticle',
            old_name='urlToImage',
            new_name='url_to_image',
        ),
        migrations.AddIndex(
            model_name='favoritearticle',
            index=models.Index(
                fields=['user', 'published_at'], name='news_favori_user_id_ffa900_idx'
            ),
        ),
    ]
