# Generated by Django 5.2.7 on 2025-12-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_favoritearticle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritearticle',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='source',
            field=models.CharField(null=True, verbose_name='название источника'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='title',
            field=models.CharField(null=True, verbose_name='заголовок'),
        ),
    ]
