# Generated by Django 5.2.7 on 2025-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_favoritearticle_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritearticle',
            name='author',
            field=models.CharField(null=True, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='category',
            field=models.CharField(null=True, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='content',
            field=models.TextField(null=True, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='url_to_image',
            field=models.URLField(null=True, verbose_name='ссылка на изображение'),
        ),
    ]
