# Generated by Django 5.2.7 on 2025-12-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_favoritearticle_author_and_more'),
        ('users', '0006_alter_profile_attempts_count_alter_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritearticle',
            options={
                'ordering': ['-published_at'],
                'verbose_name': 'featured_news',
                'verbose_name_plural': 'selected_news',
            },
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='author',
            field=models.CharField(null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='category',
            field=models.CharField(null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='content',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='publication_date'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='source',
            field=models.CharField(null=True, verbose_name='source_name'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='title',
            field=models.CharField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='url',
            field=models.URLField(verbose_name='link_to_news'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='url_to_image',
            field=models.URLField(null=True, verbose_name='image_link'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite_articles',
                to='users.user',
                verbose_name='user',
            ),
        ),
    ]
